version: '3.8'

services:
  db:
    container_name: parkwise_db
    image: postgres
    restart: always
    ports:
      - 2010:5432
    environment:
      POSTGRES_USER: sahilverma
      POSTGRES_DB: parkwise
      POSTGRES_PASSWORD: sahilverma
    volumes:
      - db_data_parkwise:/var/lib/postgresql/data
volumes:
  db_data_parkwise:
